[build-system]
requires = ["setuptools==70.0.0", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "MAST3R-FUSION"
version = "0.0.1"
dependencies = [
    "numpy==1.26.4",
    "einops",
    "pyrealsense2",
    "evo",
    "natsort",
    "pykdtree",
    "torchcodec==0.1",
    "foxglove-websocket==0.1.4",
    "websockets==10.4",
    "lietorch @ git+https://github.com/princeton-vl/lietorch.git",
    "plyfile",
    "cotracker @ git+https://github.com/facebookresearch/co-tracker.git",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mast3r_fusion*"]
namespaces = false
